### ISSUE TITLE
Code generation with Zserio 2.11.0

### ISSUE THREAD

**Issue by jo-me** [woven-planet/go-zserio#108] opened 2023-07-21 12:24 UTC
Hi,

generating code based on newer schema versions (2023.6 - which apparently requires zserio 2.11.0) yields a lot of errors.

In addition to the one reported in #107 which was there in earlier versions as well the code generator stops with the message
`Error: parse schema: eval structs: evaluate "0.0": unknown expression type`
without giving any hint where this is (probably related to the formulas in PercentageRange & PercentagePosition).

If I remove the "+0.0" in those formulas the code generation  ends with a different error:
`Error: parse schema: eval structs: evaluate ".": failed to evaluate dot expression` - again without a hint where this happened.

Aside from that there are many strange outputs that were not there with schemas based on zserio 2.10.0 which leads me to believe that something is not compatible anymore with go-zserio:

```
2023/07/21 14:16:46 Parsing file zs/core/types.zs...
line 282:1 reportAttemptingFullContext d=59 (expression), input='>minScaleDenominator;};'
line 281:61 reportContextSensitivity d=59 (expression), input='>'
line 422:27 reportAttemptingFullContext d=59 (expression), input='>startPosition;/** End percentage position on the feature.*/bit<numBits>endPosition:'
line 419:28 reportContextSensitivity d=59 (expression), input='>startPosition;'
line 424:2 reportAttemptingFullContext d=59 (expression), input='>endPosition:endPosition>startPosition;function'
line 422:27 reportContextSensitivity d=59 (expression), input='>endPosition:'
line 424:2 reportAttemptingFullContext d=59 (expression), input='>startPosition;function'
line 422:41 reportContextSensitivity d=59 (expression), input='>'
line 444:2 reportAttemptingFullContext d=59 (expression), input='>position;function'
line 442:23 reportContextSensitivity d=59 (expression), input='>position;'
```

```
2023/07/21 14:16:46 Parsing file zs/display/types.zs...
line 3405:2 reportAttemptingFullContext d=59 (expression), input='>elevation;/** Normal vector. */NormalSphere'
line 3402:30 reportContextSensitivity d=59 (expression), input='>elevation;'
```
Are you planning to support the newer schema versions along with the newer zserio versions?

Thanks!

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Danaozhong** [comment] 2023-07-28 10:12
Thank you for the problem report.

To fully support zserio 2.11.0, I took the first small step and updated the antlr definition files to the latest version: https://github.com/woven-planet/go-zserio/pull/110 
This should resolve some of the parsing issues.

The `0.0` error is caused by `go-zserio` not supporting float expressions so far. Let me work on a PR to close this gap.

The dot expression error looks strange. I will have a look at the `display` module and see if I can reproduce it.

In general, we want to keep the code up-to-date and in sync with the latest zserio developments.

**Comment by Danaozhong** [comment] 2023-07-31 03:00
I was able to reproduce the `parse schema: eval structs: evaluate ".": failed to evaluate dot expression` issue.

The problem happens when evaluating a dot expression on an Enumeration. If the left operand is not the Enumeration type itself, but a zserio `subtype` that is mapped to the Enumeration, the exception will occur.

For example:
```
enum uint32 testEnum
{
    RED,
    BLUE,
};

subtype testEnum subtypeEnum;
```


trying to evaluate
`subtypeEnum.RED`
will fail, because of the subtyping in between. The dot expression evaluation needs to be improved to consider cases where subtyping is used, and look up the fundamental `enum` type correctly.

**Comment by jo-me** [comment] 2023-08-17 07:13
Thanks @Danaozhong for taking care of these compatibility issues. I do not see strange output during code generation anymore.

However, the generated code contains several (types of) errors.

e.g. the place where the 0.0 was in the zs file defined yields an UNSUPPORTED_TYPE in the go output file.

```
func (v *PercentagePosition) PercentageValue() float64 {
	retVal := (v.Position + UNSUPPORTED_TYPE) / ((1 << v.NumBits) - 1)
	return float64(retVal)
}
```

Would you rather have all the error details in this issue or a separate one for each error?


Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by Danaozhong** [comment] 2023-08-21 03:12
@jo-me Thank you so much again for checking with the updated code!

The float code generation issue should be resolved with https://github.com/woven-planet/go-zserio/pull/118.

Could you please let me know what other issues you are encountering? Please feel free to provide the error details altogether here!

**Comment by jo-me** [comment] 2023-08-21 07:46
Ok, so in display layer there are two more:

**1) undefined: index** 

At the end of the line below: 

```
func (v *Mesh3DRenderLayerData) UnmarshalZserio(r zserio.Reader) error {
...
Mesh3DRenderDataArrayProperties.ArrayTraits.DefaultObject.Mesh = core_geometry.PolyMesh3D(v.Mesh3dDisplayGeometryLayer.Buffers.Meshes3D.Polymeshes[index])
...
}
```

**2) type mismatch int uint64**
in bdam surface type:

```
func (v *BdamSurface) NumVertices() uint64 {
	retVal := len(v.Vertices) + v.NumGridVertices()
	return uint64(retVal)
}
```

len(..) returns int, NumGridVertices uint64

**Comment by Danaozhong** [comment] 2023-08-22 23:53
Thank you very much for the issue summary!
Issue (1) is the missing support for the `@index` operator (https://github.com/woven-planet/go-zserio/issues/115). Let me have a look if there is a simple fix for that.

Issue (2) Is an issue on type casts for different bit length or signed/unsigned mismatches when combining integer types. C++ and Python do implicit type conversions, so for Go we will need to generate type casts explicitly. I have created https://github.com/woven-planet/go-zserio/issues/120 and a PR to address that.

**Comment by jo-me** [comment] 2023-08-24 07:49
I can confirm that issue (2) is resolved with the latest version. 
Since you have created a separte issue for (1) I guess this one can be closed if you like. 

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by wichert** [comment] 2023-08-24 07:52
Thanks for the confirmation @jo-me. I'll close this issue.

**Closed by wichert** 2023-08-24 07:52 UTC

**Comment by Danaozhong** [comment] 2023-08-31 07:32
@jo-me All issues I am aware of are fixed, and merged with `main`. Could you please try another test run, and see if you still see any issues?

**Comment by jo-me** [comment] 2023-08-31 09:09
Hi @Danaozhong, 
I've updated to release v0.7.0 and regenerated everything. The @index errors have now also disappeared and I do not see any other compilation issues.

Thanks a lot for your efforts!


Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
